### ISSUE TITLE
 send the phone number

### ISSUE THREAD

**Issue by LCB0B** [torresflo/PyReal#1]
Hi, nice work, 
I tried many many times, it never worked :/

keep getting the error : " Exception: Error when sending the OTP request. Probably the quota is exceeded, try again."

**Comment by NicoWeio** [comment]
How often did you try exactly? If this boils down to the same error described in https://github.com/notmarek/BeFake/issues/49, you might succeed if you just try a few more times, even in quick succession.

**Comment by torresflo** [comment]
Hi @LCB0B  thanks for letting me know and sorry for the long delay reply.
I developed this project just as a personal challenge and for some friends. I am not currently actively working on it anymore (and I am not even sure if it is still working or not. Apparently no).
You can have a look at BeFake as suggested that seems to have resolved the issue.
