### ISSUE TITLE
Similar project: BeFake

### ISSUE THREAD

**Issue by NicoWeio** [torresflo/PyReal#2]
I just wanted to let you (@torresflo and everyone else who might read this) know that there is https://github.com/notmarek/BeFake, which seems to do basically the same thing and – as of now – is more popular. I haven't looked at _this_ project in much detail, but it made a nice and clean first impression on me. Maybe we (as in _PyReal_ and _BeFake_) could join forces? :)

**Comment by torresflo** [comment]
Hi @NicoWeio, thanks for letting me know and sorry for the long delay reply.
I developed this project just as a personal challenge and for some friends. I am not currently actively working on it anymore (and I am not even sure if it is still working or not). 
I will have a look at BeFake and see if I can contribute to it at some point.
